name: Website CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check website files
        run: |
          test -f index.html
          test -f Dockerfile

  build:
    needs: test
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set image tag
        id: tag
        run: echo "image_tag=${{ github.run_number }}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-website:${{ steps.tag.outputs.image_tag }} .

      - name: Save Docker image
        run: |
          docker save \
            ${{ secrets.DOCKER_USERNAME }}/ci-website:${{ steps.tag.outputs.image_tag }} \
            -o ci-website.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ci-website.tar

  push:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: load Docker image
        run: docker load -i ci-website.tar
#i means input file

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-website:${{ needs.build.outputs.image_tag }}
  # deploy:
  #   needs: [build, push]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to EC2
  #       uses: appleboy/ssh-action@v1.2.2
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USERNAME }}
  #         key: ${{ secrets.EC2_SSH_KEY }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/ci-website:${{ needs.build.outputs.image_tag }}

  #           docker stop my-websb || true
  #           docker rm my-websb || true

  #           docker run -d \
  #             --name my-websb \
  #             -p 8081:80 \
  #             ${{ secrets.DOCKER_USERNAME }}/ci-website:${{ needs.build.outputs.image_tag }}
  deploy:
    needs: [build, push]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy new version
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            IMAGE="${{ secrets.DOCKER_USERNAME }}/ci-website:${{ needs.build.outputs.image_tag }}"

            echo "Pulling new image..."
            docker pull $IMAGE

            echo "Removing previous temporary container if it exists..."
            docker stop my-websb-new || true
            docker rm my-websb-new || true

            echo "Starting new version on port 8082..."
            docker run -d \
              --name my-websb-new \
              -p 8082:80 \
              $IMAGE

            echo "Waiting for application..."
            sleep 5

            echo "Running health check..."
            curl --fail http://localhost:8082

            echo "Health check successful!"

            OLD_IMAGE=$(docker inspect --format='{{.Config.Image}}' my-websb)
            echo "Old image: $OLD_IMAGE"

            docker stop my-websb
            docker rm my-websb

            docker stop my-websb-new
            docker rm my-websb-new

            docker run -d \
             --name my-websb \
            -p 8081:80 \
            $IMAGE
            sleep 5

            if curl --fail http://localhost:8081; then
                echo "New deployment is healthy!"
            else
                echo "New deployment failed! Rolling back..."

                docker stop my-websb || true
                docker rm my-websb || true

                docker run -d \
                  --name my-websb \
                  -p 8081:80 \
                  $OLD_IMAGE

                sleep 5

                curl --fail http://localhost:8081
            fi